CREATE TABLE "customers" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(50),
  "gender" varchar(50),
  "city" varchar(50),
  "pet_preferences" varchar(50),
  "date_of_birth" date,
  "state" varchar(50)
);

CREATE TABLE "species" (
  "species_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "species_name" varchar(50)
);

CREATE TABLE "subspecies" (
  "subspecies_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subspecies_name" varchar(50),
  "species_id" int
);

CREATE TABLE "pets" (
  "pet_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_name" varchar(50),
  "species_id" int,
  "subspecies_id" int,
  "age_dec_2023" int,
  "year_of_birth" date,
  "arrival_date" date,
  "gender" varchar(50),
  "aggressiveness" varchar(50),
  "adopted_status" varchar(10)
);

CREATE TABLE "adoptions" (
  "adoption_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "pet_id" int,
  "adoption_date" date,
  "adoption_event_id" int
);

CREATE TABLE "adoption_events" (
  "adoption_event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_name" varchar(100),
  "event_date" date,
  "city" varchar(100),
  "state" varchar(50)
);

CREATE TABLE "feedback" (
  "feedback_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_id" int,
  "feedback_date" date,
  "overall_rating" int,
  "adoption_process_rating" int,
  "pet_condition_rating" int,
  "staff_interaction_rating" int,
  "post_adoption_support_rating" int,
  "follow_up_required" boolean
);

CREATE TABLE "health_records" (
  "health_record_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pet_id" int,
  "checkup_date" date,
  "health_status" varchar(50),
  "vaccination_status" varchar(50)
);

CREATE TABLE "traits" (
  "trait_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "personality_trait" varchar(50)
);

CREATE TABLE "pet_traits" (
  "pet_id" int,
  "trait_id" int,
  PRIMARY KEY ("pet_id", "trait_id")
);

ALTER TABLE "subspecies" ADD FOREIGN KEY ("species_id") REFERENCES "species" ("species_id");

ALTER TABLE "pets" ADD FOREIGN KEY ("species_id") REFERENCES "species" ("species_id");

ALTER TABLE "pets" ADD FOREIGN KEY ("subspecies_id") REFERENCES "subspecies" ("subspecies_id");

ALTER TABLE "adoptions" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id");

ALTER TABLE "adoptions" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "adoptions" ADD FOREIGN KEY ("adoption_event_id") REFERENCES "adoption_events" ("adoption_event_id");

ALTER TABLE "feedback" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id");

ALTER TABLE "health_records" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "pet_traits" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "pet_traits" ADD FOREIGN KEY ("trait_id") REFERENCES "traits" ("trait_id");
